### PR TITLE
FastBoot 1.0 compatibility

### PR DESCRIPTION
**Pull request by lucacorti**
This fixes FastBoot compatibility breaking changes.

### CODE REVIEW

**Comment by altrim** [comment]
@lucacorti Looks like the build is failing with `Cannot find module 'broccoli-stew'`. You should probably add it as dependency in `package.json`

**Comment by lucacorti** [comment]
The build works for me, but adding it anyway.

**Comment by altrim** [comment]
@lucacorti Thanks for the PR 👍

**Comment by lucacorti** [comment]
Sorry, couldn't figure out why the build was still failing.

**Pull request merged**
