### PR TITLE
Option to disable default/built-in styles

### PR DESCRIPTION
**Pull request by thefuzz80**

### CODE REVIEW

**Comment by thefuzz80** [comment]
@altrim  Let me know if you would like me to update the readme.md as well.  If so I issue a new pull request with that update.

**Comment by altrim** [comment]
@thefuzz80 Yeah it would be good to have it in the readme as well.

**Comment by altrim** [comment]
Great, thanks a lot for the PR.

**Comment by thefuzz80** [comment]
My very first one!  Thanks!

**Pull request merged**
